name: Build and Test

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.100'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Debug: List repository contents
      run: |
        echo "Listing root directory:"
        ls -la
        echo "Listing subdirectories:"
        ls -R

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore AirportTicketBookingExerciseSOLIDPrinciples.sln

    - name: Build solution
      run: dotnet build AirportTicketBookingExerciseSOLIDPrinciples.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test AirportTicketBookingExerciseSOLIDPrinciples.sln --no-restore --verbosity normal
