name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '8.0.100' # Update to .NET 8.0 SDK version

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
      - name: Build
      run: dotnet build AirportTicketBookingExerciseSOLIDPrinciples.sln --configuration Release --no-restore --verbosity normal /t:Build
    
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      


      - name: Build with diagnostics
        run: dotnet build AirportTicketBookingExerciseSOLIDPrinciples.sln --configuration Release --no-restore --verbosity diagnostic

        - name: Debug Build and Test
          run: |
            set -e
            dotnet restore
            dotnet build AirportTicketBookingExerciseSOLIDPrinciples.sln --configuration Release --no-restore --verbosity normal
            dotnet test --no-restore --verbosity normal

